name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@master
    # Build action
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    # Deploy action
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: 'https://gateway.eu1.storjshare.io' # optional: default to s3.amazonaws.com
        SOURCE_DIR: 'dist/apps/web'      # optional: defaults to entire repository
        
        
 # more detail: https://github.com/marketplace/actions/s3-sync